### PR TITLE
feat: Add support for Next13 App Directory

### PR DESCRIPTION
**Pull request by Gawdfrey**
_First of all, all credit to @catlan for the initial PR, this is just an extension of his work._

I quickly coded this up and there is still a few things missing, but I wanted to share how we could solve it. I have yet to confirm that it actually works and runs in a proper environment.

The code is a bit verbose, but that is to respect the rule of hooks that say that hooks can not be conditional. The new app directory requires the "use client" syntax at the top to allow the usage of hooks as well as that the Script tag does not work client side (I have no official source on this, except experience after working with it today..). Therefore we conditionally render the components that in turn run the separate hooks.

I hope this makes sense to anyone else, I'll try to finish up the PR this week (No promises) if we agree that this is the way forward.

TODO:

- [ ]  Make current tests pass
- [ ]  Create new tests that covers new functionality
- [ ]  Update Readme that covers new functionality
- [ ]  Extract types to external types file for better sharing of types (?)

### CODE REVIEW

**Comment by MauricioRobayo** [comment]
thank youuuuuuu @Gawdfrey , I just skimmed through it and looks great so far, I like this approach, makes sense.

Looking forward to testing this myself hopefully in the next few days, hope you have the time to complete it soon but no rush, I really appreciate you are taking some of your free time to add this feature!

**Comment by MauricioRobayo** [comment]
Maybe we can get rid of the prop and just let it automatically detect which one should be used 🤔 ... do you think that would be possible @Gawdfrey ?

**Comment by Gawdfrey** [comment]
> Maybe we can get rid of the prop and just let it automatically detect which one should be used 🤔 ... do you think that would be possible @Gawdfrey ?

There is probably a possibility of doing that. But after working with the app directory and reading the docs some more, I am unsure if sharing the same component is the correct approach. The issue lies within shipping the hook with the component. This is because you would usually place the component in the Layout file, [which does not re-render during navigation](https://beta.nextjs.org/docs/api-reference/file-conventions/layout). 

I therefore propose that we create a new component for the component for the app directory that does not include the hook, allowing the user to place the component where they please and use the hook if wanted and in the correct files. (e.g [in the template file](https://beta.nextjs.org/docs/routing/pages-and-layouts#templates) which does re-render during navigation and can be co-placed with the layout file)

**Comment by Gawdfrey** [comment]
I made some changes to the PR that reflect my latest comment. Let me know if this makes sense.
We should probably wait until the app directory is stable before including this as there is a chance stuff still might change. Or include it under an unstable flag.

**Comment by qunash** [comment]
Any updates?

**Comment by MauricioRobayo** [comment]
Nextjs is planning to add [third party scripts](https://github.com/vercel/next.js/discussions/48256) support.

Seems like they will add support for [Google Tag Manager and Gtag](https://github.com/vercel/next.js/discussions/53868).

That will soon become the recommended way to add Google Analytics and this package will no longer be needed.

Thanks for the effort you have put into this PR @Gawdfrey !

**Pull request closed without merging**
