### PR TITLE
Replace Router.events for Next.js 13

### PR DESCRIPTION
**Pull request by catlan**
related to #304

### CODE REVIEW

**Comment by MauricioRobayo** [comment]
This is awesome, thanks @catlan !

This is not going to be backwards compatible with Next < v13, right?

**Comment by catlan** [comment]
> import { usePathname, useSearchParams } from "next/navigation"

Are new to Next.js 13, so  it is not backwards compatible.

**Comment by MauricioRobayo** [comment]
> Not sure if this is related to the changes in this pull request or if the bug exists in current version as well, but for every page view I see two page_view events in the DebugView. I verified that function pageView is only called once per page change. So I assume the gtag is setup up to track page changes as well.

Hi @catlan ! Do you think it could be related to [this](https://github.com/MauricioRobayo/nextjs-google-analytics/pull/315#issuecomment-1327912439)?

Can you check if upgrading to v2.2.2 solves the issue?

**Comment by MauricioRobayo** [comment]
btw @catlan , I'm not feeling very confortable with not making this library compatible with Next < v13, I'm wondering if there could be a way to make it compatible both with >=v13 and <v13. I'm drowning at my job so haven't been able to check this more carefully. I apologize for that, will take the time to come back to this soon.

**Comment by catlan** [comment]
> > Not sure if this is related to the changes in this pull request or if the bug exists in current version as well, but for every page view I see two page_view events in the DebugView. I verified that function pageView is only called once per page change. So I assume the gtag is setup up to track page changes as well.
> 
> Hi @catlan ! Do you think it could be related to [this](https://github.com/MauricioRobayo/nextjs-google-analytics/pull/315#issuecomment-1327912439)?
> 
> Can you check if upgrading to v2.2.2 solves the issue?

I believe the reason for it is analytics [enhanced event measurement](https://support.google.com/analytics/answer/9216061?hl=en). `page_view`:

> An advanced setting on this option controls whether the event is sent based on browser-history events. This measurement option listens for pushState, popState, and replaceState.

**Comment by Gawdfrey** [comment]
The simplest way to keep this change non-breaking would to keep the functionality the same in the usePageViews and create a new hook that implements the next/navigation way. You can run one of them based on a new argument to the <GoogleAnalytics/> component. Maybe something called appDirectory? This argument defaults to false, so that it does not break current usages, but allows it to be incrementally adopted when used in the app directory.

**Comment by MauricioRobayo** [comment]
I can take a crack at finalising this PR this week if wanted?

@Gawdfrey That would be awesome! And I like your proposal for making it a new opt-in hook so people can migrate when they desire without breaking current functionality.

**Pull request closed without merging**
